# toy dataset test
python main.py --model_name FM --emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --topk 3,5 --path ../data/
python main.py --model_name AFM --emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --topk 3,5 --path ../data/
python main.py --model_name xDeepFM --emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --topk 3,5 --path ../data/
python main.py --model_name DIN --emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --topk 3,5 --path ../data/
python main.py --model_name CAN --emb_size 64 --dataset MIND_toy --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --path ../data/
python main.py --model_name LightGCN --emb_size 64 --path ../data/ --dataset MIND_toy --topk 3,5
python main.py --model_name SASRec --emb_size 64 --path ../data/ --dataset MIND_toy --topk 3,5 --include_context_features 1 --include_item_features 1

python main.py --model_name FM_SARE --emb_size 64 --situ_emb_size 64 --dataset MIND_toy --path ../data/ --include_context_features 1 --include_item_features 1 --select_situations c_weekday,c_period,c_isweekend,c_hour --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
python main.py --model_name AFM_SARE --emb_size 64 --situ_emb_size 64 --dataset MIND_toy --path ../data/ --include_context_features 1 --include_item_features 1  --select_situations c_weekday,c_period,c_isweekend,c_hour --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
python main.py --model_name xDeepFM_SARE --emb_size 64 --situ_emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --select_situations c_weekday,c_period,c_isweekend,c_hour --topk 3,1,5 --path ../data/ --avg_method har_weights --situ_fusion_method attention_new
python main.py --model_name DIN_SARE --emb_size 64 --dataset MIND_toy --include_context_features 1 --include_item_features 1 --topk 3,5 --path ../data/ --select_situations c_weekday,c_period,c_isweekend,c_hour --avg_method har_weights --situ_fusion_method attention_new
python main.py --model_name CAN_SARE --dataset MIND_toy --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --path ../data/ --avg_method har_weights --situ_fusion_method attention_new

python main.py --model_name LightGCN_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND_toy --topk 3,5 --include_context_features 1 --include_item_features 1 --select_situations c_weekday,c_period,c_isweekend,c_hour
python main.py --model_name SASRec_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND_toy --topk 3,5 --include_context_features 1 --include_item_features 1 --select_situations c_weekday,c_period,c_isweekend,c_hour --avg_method har_weights --situ_fusion_method attention_new


# # backbone on MIND
# python main.py --model_name FM --emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --loss_n BPRsession --lr 2e-3 --l2 2e-5 --topk 3,1,5,10 --path ../data/
# python main.py --model_name AFM --emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --loss_n BPRsession --lr 1e-3 --l2 1e-6 --topk 3,1,5,10 --path ../data/ --attention_size 128 --dropout_prob 0.8 --reg_weight 2e-1
# python main.py --model_name xDeepFM --emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --loss_n BPRsession --lr 1e-2 --l2 1e-6 --topk 3,1,5,10 --path ../data/ --dropout_prob 0.2 --reg_weight 1e-2 --layers "[64,64]"
# python main.py --model_name DIN --emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --eval_batch_size 128 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --topk 3,1,5,10 --path ../data/ --dropout 0 --dnn_layers "[128,64]" --history_max 25
# python main.py --model_name CAN --emb_size 64 --dataset MIND --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --eval_batch_size 64 --path ../data/ --lr 2e-4 --l2 1e-4 --din_dnn_layers "[128,64]" --dnn_layers "[128,32]" --att_layers "[64]" --orders 1 --history_max 25 --induce_vec_size 512 --feed_vec_size 32
# python main.py --model_name LightGCN --emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5,10 --lr 1e-3 --l2 1e-6 --n_layers 6
# python main.py --model_name SASRec --emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5 --lr 5e-3 --l2 1e-4 --include_context_features 1 --include_item_features 1 --num_layers 1 --num_heads 2

# # SARE on MIND
# python main.py --model_name FM_SARE --emb_size 64 --situ_emb_size 64 --dataset MIND --path ../data/ --include_context_features 1 --include_item_features 1 --situ_weights 0.1 --prob_weights 0.2 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --lr 2e-3 --l2 1e-5 --situ_lr 2e-3 --situ_l2 0 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name AFM_SARE --emb_size 64 --attention_size 128 --dropout_prob 0.8 --reg_weight 2e-1 --situ_emb_size 64 --dataset MIND --path ../data/ --include_context_features 1 --include_item_features 1 --situ_weights 0.1 --prob_weights 0.1 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --lr 5e-3 --l2 1e-6 --situ_lr 1e-3 --situ_l2 1e-6 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name xDeepFM_SARE --train_max_neg_item 50 --train_max_pos_item 30 --emb_size 64 --situ_emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --situ_weights 0.2 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --lr 1e-2 --l2 1e-6 --situ_lr 1e-2 --situ_l2 0 --topk 3,1,5 --path ../data/ --dropout 0.5 --reg_weight 1e-2 --layers "[128,32]" --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name DIN_SARE --emb_size 64 --dataset MIND --include_context_features 1 --include_item_features 1 --eval_batch_size 64 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --topk 3,5 --path ../data/ --dropout 0 --dnn_layers "[128,64]" --history_max 25 --situ_weights 0.1 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 1e-3 --situ_l2 1e-6 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name CAN_SARE --dataset MIND --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --eval_batch_size 64 --path ../data/ --lr 2e-4 --l2 1e-4 --din_dnn_layers "[128,64]" --dnn_layers "[128,32]" --att_layers "[64]" --orders 1 --history_max 25 --induce_vec_size 512 --feed_vec_size 32 --loss_n BPRsession --situ_weights 0.5 --prob_weights 0.05 --prob_loss_n Logposavg --situ_loss_n BPRsession --temperature 5 --situ_lr 1e-3 --situ_l2 0 --avg_method har_weights --situ_fusion_method attention_new

# python main.py --model_name LightGCN_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5 --lr 5e-3 --l2 1e-6 --n_layers 6 --include_context_features 1 --include_item_features 1 --situ_weights 1 --prob_weights 0.1 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 1e-3 --situ_l2 0 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name LightGCN_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5 --lr 1e-3 --l2 1e-6 --n_layers 6 --include_context_features 1 --include_item_features 1 --situ_weights 0.5 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 2e-3 --situ_l2 0 --avg_method har_weights --situ_fusion_method attention_new --fix_rec 1 --rec_path ../model/LightGCN_imp/MIND_best.pt
# python main.py --model_name SASRec_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5 --lr 5e-3 --l2 1e-4 --include_context_features 1 --include_item_features 1 --num_layers 1 --num_heads 2 --situ_weights 0.2 --prob_weights 0.1 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 1e-3 --situ_l2 1e-4 --avg_method har_weights --situ_fusion_method attention_new --fix_rec 1 --rec_path ../model/SASRec_imp/MIND_best.pt
# python main.py --model_name SASRec_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset MIND --topk 3,1,5 --lr 5e-3 --l2 1e-4 --include_context_features 1 --include_item_features 1 --num_layers 1 --num_heads 2 --situ_weights 0.2 --prob_weights 0.5 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 5e-3 --situ_l2 1e-6 --avg_method har_weights --situ_fusion_method attention_new


# # backbone on KuaiRand
# python main.py --model_name FM --emb_size 64 --dataset KuaiRand_1k --include_context_features 1 --include_item_features 1 --include_user_features 1 --loss_n BPRsession --lr 7e-4 --l2 1e-6 --topk 3,1,5,10 --path ../data/
# python main.py --model_name AFM --emb_size 64 --dataset KuaiRand_1k --include_context_features 1 --include_item_features 1 --include_user_features 1 --loss_n BPRsession --lr 5e-4 --l2 1e-7 --topk 3,1,5,10 --path ../data/ --attention_size 128 --eval_batch_size 16 --dropout_prob 0.8 --reg_weight 5e-3
# python main.py --model_name xDeepFM --emb_size 64 --dataset KuaiRand_1k --include_user_features 1 --include_context_features 1 --include_item_features 1 --eval_batch_size 32 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --topk 3,1,5,10 --path ../data/ --dropout_prob 0 --reg_weight 0 --layers "[64,64]"
# python main.py --model_name DIN_imp --emb_size 64 --dataset KuaiRand_1k --include_context_features 1 --include_item_features 1 --include_user_features 1 --eval_batch_size 64 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --topk 3,1,5,10 --path ../data/ --dropout 0 --dnn_layers "[64]" --history_max 8
# python main.py --model_name CAN_DIN --dataset KuaiRand_1k --include_user_features 1 --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --eval_batch_size 64 --path ../data/ --lr 2e-4 --l2 1e-4 --history_max 15 --din_dnn_layers "[64]" --dnn_layers "[256]" --att_layers "[64]" --orders 3 --induce_vec_size 256 --feed_vec_size 8 --dropout 0
# python main.py --model_name LightGCN_imp --emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5,10 --lr 5e-3 --l2 1e-6 --n_layers 6
# python main.py --model_name SASRec_imp --emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5 --lr 5e-3 --l2 1e-6 --include_context_features 1 --include_item_features 1 --num_layers 3 --num_heads 4 --history_max 20

# # SARE on KuaiRand

# python main.py --model_name FM_SARE --emb_size 64 --situ_emb_size 64 --dataset KuaiRand_1k --path ../data/ --include_context_features 1 --include_item_features 1 --include_user_features 1 --situ_weights 0.1 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --lr 1e-3 --l2 1e-6 --situ_lr 2e-3 --situ_l2 1e-6 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name AFM_SARE --emb_size 64 --attention_size 64 --eval_batch_size 32 --dropout_prob 0.8 --reg_weight 1e-2 --situ_emb_size 64 --dataset KuaiRand_1k --path ../data/ --include_context_features 1 --include_item_features 1 --include_user_features 1 --situ_weights 0.05 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature --lr 2e-3 --l2 1e-6 --situ_lr 2e-3 --situ_l2 1e-6 --topk 3,1,5 --avg_method math_weights --situ_fusion_method attention_new
# python main.py --model_name xDeepFM_SARE --emb_size 64 --situ_emb_size 64 --train_max_neg_item 50 --train_max_pos_item 30 --dataset KuaiRand_1k --include_user_features 1 --include_context_features 1 --include_item_features 1 --eval_batch_size 32 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --situ_lr 1e-3 --situ_l2 0 --topk 3,1,5 --path ../data/ --dropout 0 --reg_weight 1e-4 --layers "[64,64]" --situ_weights 0.2 --prob_weights 0.05 --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name DIN_SARE --emb_size 64 --situ_emb_size 64 --dataset KuaiRand_1k --include_context_features 1 --include_item_features 1 --include_user_features 1 --eval_batch_size 64 --loss_n BPRsession --lr 5e-3 --l2 1e-6 --topk 3,5 --path ../data/ --dropout 0 --dnn_layers "[64]" --history_max 8 --situ_weights 0.5 --prob_weights 0.02 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 5e-3 --situ_l2 1e-6 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name CAN_SARE --dataset KuaiRand_1k --include_user_features 1 --include_item_features 1 --include_item_features 1 --topk 3,5 --select_situations c_weekday,c_period,c_isweekend,c_hour --eval_batch_size 64 --path ../data/ --lr 5e-4 --l2 1e-4 --history_max 15 --din_dnn_layers "[64]" --dnn_layers "[256]" --att_layers "[64]" --orders 3 --induce_vec_size 256 --feed_vec_size 8 --dropout 0 --loss_n BPRsession --situ_weights 0.5 --prob_weights 0.05 --prob_loss_n Logposavg --situ_loss_n BPRsession --temperature 5 --situ_lr 5e-4 --situ_l2 1e-6 --avg_method har_weights --situ_fusion_method attention_new

# python main.py --model_name LightGCN_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5 --lr 5e-3 --l2 1e-6 --n_layers 6 --include_context_features 1 --include_item_features 1 --include_user_features 1 --situ_weights 0.2 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 2e-3 --situ_l2 1e-6 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name LightGCN_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5 --lr 5e-3 --l2 1e-6 --n_layers 6 --include_context_features 1 --include_item_features 1 --include_user_features 1 --situ_weights 0.2 --prob_weights 0.05 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 5 --situ_lr 2e-3 --situ_l2 1e-6 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new --fix_rec 0 --rec_path ../model/LightGCN_imp/KuaiRand_best.pt
# python main.py --model_name SASRec_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5 --lr 5e-3 --l2 1e-6 --include_context_features 1 --include_item_features 1 --num_layers 3 --num_heads 4 --history_max 20 --situ_weights 0.2 --prob_weights 0.02 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 10 --situ_lr 5e-3 --situ_l2 0 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new
# python main.py --model_name SASRec_SARE --emb_size 64 --situ_emb_size 64 --path ../data/ --dataset KuaiRand_1k --topk 3,1,5 --lr 5e-3 --l2 1e-6 --include_context_features 1 --include_item_features 1 --num_layers 3 --num_heads 4 --history_max 20 --situ_weights 0.2 --prob_weights 0.02 --loss_n BPRsession --prob_loss_n Logposavg --select_situations c_weekday,c_period,c_isweekend,c_hour --situ_loss_n BPRsession --temperature 10 --situ_lr 5e-3 --situ_l2 0 --topk 3,1,5 --avg_method har_weights --situ_fusion_method attention_new --fix_rec 0 --rec_path ../model/SASRec_imp/KuaiRand_best.pt


